### ISSUE TITLE
Multi-step nav

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/dvl-core#109]
We have a few different components for multi-step navigation. Screendoor's wizard checklist lets you navigate to any step:

![screen shot 2015-07-06 at 10 46 47 am](https://cloud.githubusercontent.com/assets/1328849/8529046/506462b2-23cc-11e5-992d-4d428b414841.png)

I dislike this component because it takes up a lot of horizontal space. Also, the "checked" status is meaningless. Just because you visited a page, filled something out on that page, or even filled out everything doesn't mean you're done with it.

(For example, you could have a rough draft of a Screendoor project description, and the checklist would still mark it as "done".)

Screendoor's bottom status bar lets you navigate to the previous / next page:

![screen shot 2015-07-03 at 7 35 21 pm](https://cloud.githubusercontent.com/assets/1328849/8506148/ce35bfec-21ba-11e5-976a-73f13fd4cd62.png)

The tabs currently in the style guide are great if you don't have to go through each step in order:

![screen shot 2015-07-03 at 7 37 28 pm](https://cloud.githubusercontent.com/assets/1328849/8506150/f63bd422-21ba-11e5-9465-4a365d06c72f.png)

And for some flows, like when sending a message or importing responses in Screendoor, we have no components.

We probably need to come up with a few different patterns. I was thinking about switching to respondent view-style pagination for the wizard. Something like:

![screen shot 2015-07-03 at 7 42 30 pm](https://cloud.githubusercontent.com/assets/1328849/8506163/d5919e5e-21bb-11e5-9b5e-06265868b28b.png)

But this wouldn't work for a linear flow like importing responses, where it doesn't make sense to jump around between steps.

**Comment by ajb** [comment]
(I think your first screenshot is not the right one.)

> Also, the "checked" status is meaningless. Just because you visited a page, filled something out on that page, or even filled out everything doesn't mean you're done with it.

I agree. A contract designer added it in ~2 years ago, and it's never made any sense to me.

>  I was thinking about switching to respondent view-style pagination for the wizard.

I'm not so sure this is a good idea. By hiding the nav items under a dropdown, we're expecting the user to know what those items are. (As well as increasing the number of clicks required to navigate to one of those items.) 

Imagine a user who's not very familiar with Screendoor knows that they need to add a new form field to their project. I think having all of the wizard steps visible makes this a lot easier than if they're hidden in a dropdown.

Anyway, I'm definitely in favor of adding a new component; in fact, this is what I had in mind when I opened https://github.com/dobtco/dvl-core/issues/55. I'll go ahead and close it now since I never really added a good enough description.

**Comment by jrubenoff** [comment]
Fixed the screenshot above. And yeah, not pushing for a specific solution, just jotting my thoughts down for reference.

In response to your concerns (again, not pushing for this, just writing down my thoughts), the dropdown makes the most sense if people are progressing through the wizard in a linear fashion, which they'll probably do the first time around, at least.

**Comment by jrubenoff** [comment]
Closing in favor of #242
