### ISSUE TITLE
Preview pages do not make enough visual distinction between examples & preview page

### ISSUE THREAD

**Issue by ajb** [dobtco/dvl-core#178]
Can anyone really tell what's going on here?

![img](http://take.ms/1mOAg)

**Comment by jrubenoff** [comment]
I've kept style overrides specific to the style guide at a minimum, so that:

a) We can keep maintenance costs to a minimum
b) The styles in the guide can match our apps as closely as possible

This comes at the expense of some visual coherence, but IMO I think it's worth the tradeoff given our bandwidth. For example, Bootstrap mitigates the problem by using padded boxes:
 
![screen shot 2015-10-05 at 5 53 57 pm](https://cloud.githubusercontent.com/assets/1328849/10297595/328841a4-6b8a-11e5-93a6-209007cfb787.png)

But this means they have at least one style override for every component:

![screen shot 2015-10-05 at 5 54 16 pm](https://cloud.githubusercontent.com/assets/1328849/10297588/20da9d26-6b8a-11e5-91ae-e9fad46250c5.png)

Let's discuss if you still think this is an issue. (Also, IMO, this is really only a problem on the Headers page.)

**Comment by ajb** [comment]
I'm not sure why you would need to add an override for each component? Why wouldn't a uniform padding (e.g. `1rem`) for the outer box work?

**Comment by jrubenoff** [comment]
Because the components themselves can have margins and padding. (For example, `.page_header` comes with an extra bottom margin, which looks ugly and inconsistent when placed in a box with other components.)

**Comment by ajb** [comment]
Ok, makes sense.
